### ISSUE TITLE
Invalid file permission after xray download

### ISSUE THREAD

**Issue by mahoor13** [hiddify/Hiddify-Reality-Scanner#12]
If you don't have Xray in the current folder, the scanner will automatically download and extract Xray to the bin folder, but it will not set execution permissions to the Xray file. As a result, you will receive an invalid file permission error.

```
PermissionError: [Errno 13] Permission denied: '/x/home/.../bin/xray'
An error occurred for yadakshenas.ir: [Errno 13] Permission denied: '/x/home/.../bin/xray'
Traceback (most recent call last):
  File "/home/.../.local/lib/python3.10/site-packages/hiddify_reality_scanner/cli.py", line 271, in test_domain_async
    p = Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

 - OS: Ubuntu
 - Version: 22.04

**Comment by hiddify-com** [comment]
is it working now?
