### ISSUE TITLE
Unable to install Xray on macOS client

### ISSUE THREAD

**Issue by AlirezaBaratian** [hiddify/Hiddify-Reality-Scanner#9]
The client cannot install Xray v1.8.6 for macOs even if the path has correct permissions or it is run as root.
It throws such "Permission denied" errors:

An error occurred for digivto.ir: [Errno 13] Permission denied: '/Users/alireza/Desktop/tmp/scan/bin/xray'
Traceback (most recent call last):
  File "/Users/alireza/.pyenv/versions/3.12.0/lib/python3.12/site-packages/hiddify_reality_scanner/cli.py", line 271, in test_domain_async
    p = Popen(
        ^^^^^^
  File "/Users/alireza/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/alireza/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/alireza/Desktop/tmp/scan/bin/xray'

**Comment by anvaari** [comment]
Solved with adding `shell=True` to 
https://github.com/hiddify/Hiddify_Reality_Scanner/blob/b0498a54e379f4460c7d18aa17769c987a2d6f69/hiddify_reality_scanner/cli.py#L271

**Comment by hiddify-com** [comment]
Please do PR

**Comment by hiddify-com** [comment]
is it fixed?
